# Use the official Python 3.9 image from Docker Hub
FROM mcr.microsoft.com/devcontainers/python:0-3.9

# [Optional] Install additional OS packages
# RUN apt-get update && apt-get install -y <your-package-list>

# [Optional] Install pip requirements
# COPY requirements.txt /tmp/pip-tmp/
# RUN pip install --no-cache-dir -r /tmp/pip-tmp/requirements.txt && rm -rf /tmp/pip-tmp
